### ISSUE TITLE
Chipped diamond is broken

### ISSUE THREAD

**Issue by tobarth** [BTNeandertha1/BTDiablo#103]
Hi, as the title says the chipped diamond affixes are broken:
![Screenshot 2024-11-19 144125](https://github.com/user-attachments/assets/bab2779f-b767-48bd-8e89-34dad0ea0485)

stats are also visible on the tooltip when hovering over with mouse when the item is on the ground. The gem dropped from quest andariel on normal difficulty.

**Comment by imKEX257** [comment]
intentional - people used to abuse chipped and flawed gems to get 28max dmg, chipped and flawed gems do not exist in the mod in normal ways; exception by clicking gem shrines with no unstacked gems in the inventory due to hard coding restriction
