### ISSUE TITLE
Corruption Ideas

### ISSUE THREAD

**Issue by WolfieeifloW** [BTNeandertha1/BTDiablo#14]
- Resistance
- Physical Damage Reduction
- Skills
- Enhanced Damage
- Sockets

**Comment by hansrun** [comment]
- Ethereal
- minus enemy resistance
- FRW
- FCR
- IAS
- plus to all attributes

**Comment by Heimdell** [comment]
- Cannot Be Frozen (rare)
- +{X}% to {Element} skills damage

**Comment by WolfieeifloW** [comment]
For any ideas you have, please use the #btd-suggestions channel on Discord in the future :)
