### ISSUE TITLE
Future Ideas

### ISSUE THREAD

**Issue by WolfieeifloW** [BTNeandertha1/BTDiablo#16]
- Make wanderer do something?
- Super Chest Rarity Nerf?
- Add more evil urns?
- Buff Necromancer some how?

**Comment by Heimdell** [comment]
Please make Psychic Hammer / Mind Blast endgame-relevant.

**Comment by Heimdell** [comment]
Additional Bone Spears for Necro on some condition would be nice as well.

**Comment by coffeebe4code** [comment]
Add MSI installer which can handle most of the work of copy-pasting for an easier installation.

I understand it seems there was a part where the player must create a new character first, unless that part could be automated as well.

**Comment by stucifer86** [comment]
Proposal: 
A new item, that one would use in a cube recipe to generate a random jewel-like socketable item.

Fits with the theme of D2 sockets, and your corruptions modification that aims for more tailoring using the socket system.

The base socketable item would be a random drop similar to jewels and gems, but specifically designed to be combined with other items in the cube to get an array of expected + unexpected affixes.

The affixes could pull from the jewel list, or perhaps a custom set of affixes. A custom set I envision would be somewhat weaker individually than jewel affixes.  The crafting recipe would give 1-2 guaranteed affixes with a small roll range and then generate a set of 2+ random affixes.

This could be balanced to keep a "best meta" socketable from evolving too narrowly, but also potentially make the player less reliant on harsh RNG for too-specific items to push the next act of content in Insanity or beyond.  It also rewards the core gameplay loop, and adds options for additional crafting recipes (perhaps these could use PSkulls/Topaz/Diamonds).

**Comment by Wezz776** [comment]
Please revert Topaz changes. I've completed the game on hell with a Pally and love basically everything, gold matters, buying those mats, corruptions, ashes, end-game, Insanity all A85 etc etc, but you do sacrifice other stats to wear Topaz pieces, need some way to begin magic finding. Even with potion you're still at -50% by default. Maybe Might+Conviction+Concentration packs are a bit hard on Melee and Mercs, they often get additional auras due to the increased range.

**Comment by madmarkspl** [comment]
Make use of a forge post quest. One of my ideas was to crush annihilus there. It could either just drop something or spawn a portal to an area with monsters and drops based on anni's stats.

**Comment by mars9t** [comment]
Make use of a forge post quest. One of my ideas was to crush annihilus there. It could either just drop something or spawn a portal to an area with monsters and drops based on anni's stats.

**Comment by JWell10** [comment]
Make Telekinesis grab ANY items

**Comment by JWell10** [comment]
Refund Gems and Runes when unsocket

**Comment by JWell10** [comment]
Make ranged attack/spell/aoe break pots

**Comment by BurritoBoracho** [comment]
First I want to thank you for the mod, made me re-play d2 after months!

What about making barb's WW proc wepon effects on hits? Maybe too OP, sounds fun xd

**Comment by thesilv3r** [comment]
Alternative method to give AOE to melee classes: add a cube recipe for weapons that uses exploding or gas potions which procs an explosion or poison cloud on striking.

**Comment by BurritoBoracho** [comment]
> Alternative method to give AOE to melee classes: add a cube recipe for weapons that uses exploding or gas potions which procs an explosion or poison cloud on striking.

CTC corpes explosion on kill would be nice

**Comment by greenonyxgaming** [comment]
i would love to be able to make runewords out of rares and magic items

**Comment by WolfieeifloW** [comment]
For any ideas you have, please use the #btd-suggestions channel on Discord in the future :)
