### ISSUE TITLE
Sort inventory issue

### ISSUE THREAD

**Issue by Mastadon85** [BTNeandertha1/BTDiablo#26]
using a controller, one can press Right Stick to sort inventory. This will move items to the 4 slots on the right where it looks like you have 4 "An Evil Force" charm like items. The evil forces will then move into your usable inventory. Now the player can pick up the evil force and drop it, eliminating the -30 all res and -199 MF.

Perhaps unbind the right stick button in the controls? or find a way to disable the sorting feature?

**Comment by WolfieeifloW** [comment]
@BTNeandertha1 any update on this?

**Comment by denvercoder** [comment]
I also noticed that when you do this sort some of your items can "stick" to the right edge of the inventory screen and you can't select them or move them.

**Comment by WolfieeifloW** [comment]
Known bug. No foreseeable fix.
