### ISSUE TITLE
The application encountered an unexpected error - after patch update.

### ISSUE THREAD

**Issue by etetreau88** [BTNeandertha1/BTDiablo#30]
After updating the patch, I can no longer log into D2R. I have determined this has to do with my character save files, though I dont really want to have to start the grind all over. Do you know if there are any fixes for this?

**Comment by WolfieeifloW** [comment]
g1oomey had a step-by-step on how to save your character. Not sure if it still works but find it here: https://discord.com/channels/238094051138600962/995888604998021180/996584281856016415
