### ISSUE TITLE
My character's magicfind value is -199%

### ISSUE THREAD

**Issue by bitibomer** [BTNeandertha1/BTDiablo#33]
My character's magicfind value is -199%. is this intentional? or it's a bug? ( if it is intentional, when will the value go to 0?)

**Comment by aglarcz** [comment]
https://github.com/BTNeandertha1/BTDiablo#game "Negative 199 MF" intentional forever

**Comment by bitibomer** [comment]
Thank you. if you don't mind explain, what is the reason to put in "negative 199 MF"? is it because the increase in MF value from other item/runeword?

**Comment by aglarcz** [comment]
No idea, i am just random fan. You can use my fork here on github, if u wish. It has some tweaks to make it little bit easier.

**Comment by WolfieeifloW** [comment]
It slows down the grind as you have to accumulate MF to start getting good drops. In vanilla it's too easy to get and stack MF which leads to a fast progression to end-game.
