### ISSUE TITLE
Burial grounds wrong mob?

### ISSUE THREAD

**Issue by Akropulis** [BTNeandertha1/BTDiablo#37]
Not sure if it is really a bug but I tried entering the burial grounds to kill Blood Raven and encountered an enemy I only had a hitchance of 14% on (normal mob nothing special about it) and oneshot me with every hit (almost max hit chance)

I think it was one of those act 5 undead that can stand back up after being killed with the charge attack.

**Comment by Pietroma** [comment]
I have the same problem

**Comment by haroldwong** [comment]
Same, had to kite those away to fight blood raven

**Comment by WolfieeifloW** [comment]
Blood Raven is now a key boss, so her area and minions have been buffed. This is intended.
