### ISSUE TITLE
Inventory broken column

### ISSUE THREAD

**Issue by mezen** [BTNeandertha1/BTDiablo#42]
Moving Items via ctrl + left click from stash/cube/etc. to your inventory moves the item into a broken column where the item can not be accessed!

![image](https://user-images.githubusercontent.com/1306409/214273049-5eabcd14-4592-4fcb-8b7d-4e655c0b8ed9.png)

**Comment by Staroporamen12** [comment]
Same on gamepad. It broke the game.
![obraz](https://user-images.githubusercontent.com/123892513/215343536-1ab2b769-e6e9-4cfd-8982-fff5d3511cbc.png)

**Comment by Durvann** [comment]
Same here. Was playing with controller and noticed this after auto sorting.

**Comment by WolfieeifloW** [comment]
Yes, do not use auto-sort.
