### ISSUE TITLE
some cube recepies do not work

### ISSUE THREAD

**Issue by TMANKO2** [BTNeandertha1/BTDiablo#47]
Hi, thanks for awesome mod!

I tried crafting caster gloves, does not work. Nothing happens. (magic leather gloves+Ort+PerfA+jewel)
Same with adding sockets to weapon. (white weapon+Amn+Ral+PerfA)

Random other recepies work fine :)
What am I doing wrong?

**Comment by LordWoytas** [comment]
Hi,

I have the same problem, Blood gloves craft doesnt work, I was checking recept, unstacked PRuby magic juwel + Magic heavy gloves, and nothing... Please help with this issue.

**Comment by zhanshi2009** [comment]
Yup, same here. Crafting recipes do not work in general. Unsocketing recipe also does not work.

**Comment by haroldwong** [comment]
Amulet of the viper is not working for me or im doing it wrong when trying to make a lower res wand

**Comment by zhanshi2009** [comment]
k, all recipes work, just put runes and gems with a plus sign instead.

**Comment by TMANKO2** [comment]
Thanks, with plus (stack mode) it works indeed.
