### ISSUE TITLE
sell/buy rune stack bug

### ISSUE THREAD

**Issue by lumpendog** [BTNeandertha1/BTDiablo#50]
when you sell rune stack with any qty inside to any vendor, then you can buy back this stack with full of 100pcs.
is it a bug of a "feature". it works like with town portals book and can be used to buy infinite runes, upgrading it up to ZOD, if you have enough gold ofc.

**Comment by SdxHex** [comment]
I want to believe this is a feature as gold is more valued. Stacking reduce vendor pricing and enough GF I now have 100 of every rune and never run out of standard of hero's. Spend most of the game in town crafting and gambling.

**Comment by lumpendog** [comment]
I guess it will be very easy to get runes then.. just for tons of gold you can craft any rune you want... This  "feature" reduces rune value dramatically.

**Comment by Impostor777** [comment]
Have you tried buying off mid runes this way? It cost a lot of gold to buy off a 100 stack, I'm not even sure it's possible for mid runes. Low runes get pretty cheap though, because of this bug/feature.

**Comment by Impostor777** [comment]
> Have you tried buying off mid runes this way? It cost a lot of gold to buy off a 100 stack, I'm not even sure it's possible for mid runes. Low runes get pretty cheap though, because of this bug/feature.

Well, my initial estimation was proven to be bollocks and lumpendog you were right. I bought a 100 Ber of a merchant for peanuts. Easy also for gems, runes, essences and even gambling (infinite gold). It's REALLY broken.

**Comment by BTNeandertha1** [comment]
If you read the rules you will see that’s not intended

**Comment by WolfieeifloW** [comment]
Known issue, up to the player to not abuse/ruin their own experience.
