### ISSUE TITLE
Crafting- Blood recipes

### ISSUE THREAD

**Issue by Barbatrick** [BTNeandertha1/BTDiablo#56]
Hello There,

I'm level 33 and I'm in act 5. I've tried to craft blood items and none of the recipes seems to work. 

I did a hit point amulet, but I try the blood glove,helm and amulet ilvl 35 and its not working.

Strange..

**Comment by Barbatrick** [comment]
I have found the solution...

**Comment by sapogordo420** [comment]
Sorry, how did u make it work? cuz i cant

**Comment by Barbatrick** [comment]
Keep the mats, runes, gems with the little + on, use the cube to add the stack on and it works.
