### ISSUE TITLE
Insane price for repair O_o

### ISSUE THREAD

**Issue by Barbatrick** [BTNeandertha1/BTDiablo#61]
The crafting system is just amazing. I equipped my javazon with incredible gears. 
My problem is, I rolled a gg javelin with 3 sockets that I put nice jewel, rune ect.. BUT the cost of repair is beyond madness... 250k of gold each time. 
Is this repair cost intentional? Because at this price, I can't use them.

Thanks

**Comment by moozyer** [comment]
Use cube to repair your weapon: 1 [Ort Rune] + Weapon --> Fully Repaired Weapon
