### ISSUE TITLE
Hidden item an evil force -30 all res , -199% MF

### ISSUE THREAD

**Issue by wbach** [BTNeandertha1/BTDiablo#62]
![20230204_115823](https://user-images.githubusercontent.com/13561641/216764235-06d57255-1398-4aa6-ac32-f0d298d6f89e.jpg)
This an evil force in inventory (-30 all res, -199% mf ) should be hidden? Probably show up after sort item in inventory

**Comment by WolfieeifloW** [comment]
Yes, do not sort inventory to avoid the charm 'popping out' of where it's supposed to sit.
