### ISSUE TITLE
Idea/Sugesstion: make it possible to have 3 (or more) sets for switch weapon.

### ISSUE THREAD

**Issue by moozyer** [BTNeandertha1/BTDiablo#64]
It would be great to have the possibility to have more swtich weapon options (not only two).
Usually one set is used for offence, second is pre-buff.
I really could use third one added for Tele staff, and eve a fourth one for some MF buff.

Is it possible to add more 'switch' options than just two?

**Comment by Warren1001** [comment]
not possible

**Comment by WolfieeifloW** [comment]
Not possible unfortunately.
