### ISSUE TITLE
Welcome Dialog from Deckard Cain appears on the Item when it gets identified

### ISSUE THREAD

**Issue by schoggi2108** [BTNeandertha1/BTDiablo#69]
Hi,

I have the Problem that when I identify an magic Item, the Welcome Diablo from Deckard Cain appears on the Item and I can not read the full Affixes on the Item. Can someone help me with this Bug? Thx

**Comment by WolfieeifloW** [comment]
I believe this was fixed shortly after a D2R patch that introduced it.
