### ISSUE TITLE
cube recipes do not function - socketing/crafting/some SoH-oriented recipes

### ISSUE THREAD

**Issue by patches88** [BTNeandertha1/BTDiablo#74]
attempting to socket white weapons for runewords using the correct recipe and transmute will not be accepted.

Adding to previous note - failed recipes :
- socketing vanilla white bases (weapons and armor)
- crafting (caster amulets, blood ring/weapon)
- socket removal (hel rune+TP)
- SoH gear upgrades (tested cham+ist+lem+SoH+Charsi's Malus on Enigma, rare amulet, white weapon)

Working recipes:
- upgrading runes and gems
- making items stackable/unstacked
- corruption

will continue to update when possible.

**Comment by NahBohdi** [comment]
Same.
