### ISSUE TITLE
Stamina potion

### ISSUE THREAD

**Issue by rssipper** [BTNeandertha1/BTDiablo#78]
Hi, I just noticed that after the last update (May 2nd) I cant buy Stamina potions. Is this intentional, as it is used in many recipes???

**Comment by BTNeandertha1** [comment]
Stamina stat is not used. Use walk mode

**Comment by djkoelz** [comment]
For the recipes, it seems the thawing potions can be used

**Comment by BTNeandertha1** [comment]
Yep

**Comment by rssipper** [comment]
yes, but still all info for the recipes is asking for stamina potions...
![stamina potions](https://github.com/BTNeandertha1/BTDiablo/assets/132459771/617a2adc-a669-4afe-8cdc-73f8021910a2)

**Comment by BTNeandertha1** [comment]
Ok, I'll check it out.
