### ISSUE TITLE
Craft not working

### ISSUE THREAD

**Issue by tyronejvisser** [BTNeandertha1/BTDiablo#80]
Crafting a blood helm with magic "helm", ral, p ruby, and magic jewel, and it won't work.  Tried also with tal with magic "belt", nothing.

**Comment by rssipper** [comment]
I worked fine for me. Just keep in m ind that the pRuby and Ral rune must be kept in "stack mode" -   some tips in the recopies page would be helpful.

**Comment by tyronejvisser** [comment]
In stacked mode?... Interesting.  I thought for sure you wouldn't want it in stacked mode.  I will give that a try!
