### ISSUE TITLE
GRIEF runeword is not working

### ISSUE THREAD

**Issue by rssipper** [BTNeandertha1/BTDiablo#81]
GRIEF runeword is not working.... Can't test it again - dont have another Lo/Sur..........
![Grief not working](https://github.com/BTNeandertha1/BTDiablo/assets/132459771/ae3121f1-5594-45aa-a362-dcbd25de7133)

**Comment by rssipper** [comment]
I just get some runes from the test characters - and still the same result. Call to arms is working, I will try and get some bases to test most runewords later today or tomorrow and will write back. I will focus on those that runes were changed.

**Comment by BTNeandertha1** [comment]
This is because Grief was changed to eth tir gul vex ral [image: image.png]

**Comment by rssipper** [comment]
I see,.., but do you know when you will be able to update the info in the wiki and in github, as still a lot of things are changed, but the data and recipes are with the old info?
