### ISSUE TITLE
Multiple hellfire torches are possible in inventory

### ISSUE THREAD

**Issue by wjakiela** [BTNeandertha1/BTDiablo#84]
In the inventory, there can be multiple hellfire torches. It seems that all of them are working.

**Comment by rssipper** [comment]
Yep its a feature:
Can now hold Multiple Unique Charms (Strictly for QOL not balance)
You can hold multiple anni's or Gheeds too.

**Comment by rssipper** [comment]
I have 3 anni's so far (I will not keep any SoJ ) - its too imbalanced. No stat points are need for str or dex, all res are capped... I will get soon some torches, but it is really imba.

**Comment by WolfieeifloW** [comment]
There is currently no way to limit the charms to only 1. It's up to the player to not ruin their own experience.
