### ISSUE TITLE
Azurewrath gives sanctuary aura instead of holy freeze

### ISSUE THREAD

**Issue by Grzegorz-Baran** [BTNeandertha1/BTDiablo#92]
Azurewrath gives sanctuary aura instead of holy freeze (as stated in README)

![Screenshot958](https://github.com/BTNeandertha1/BTDiablo/assets/18481234/c82e8c3b-857c-4d14-90b8-055bce4082f2)

**Comment by WolfieeifloW** [comment]
@imKEX257 which aura is it supposed to give?
