### ISSUE TITLE
Game is lagging when opening the inventory

### ISSUE THREAD

**Issue by maluramichael** [BTNeandertha1/BTDiablo#93]
I just started using this mod in conjunction with D2R Launch v1.6.7. The version iam using right now is 1.0.7.

Everytime i open the inventory the frames drop a lot.

https://github.com/BTNeandertha1/BTDiablo/assets/1489383/94c8a1b6-e021-437f-aa26-f50a9db0f5a0

**Comment by BaronBeefStick** [comment]
Has to deal with the blue boxes on the right side. If you can get rid of those it'll will be fixed. Otherwise try a newer version of BTD

**Comment by WolfieeifloW** [comment]
> Has to deal with the blue boxes on the right side. If you can get rid of those it'll will be fixed. Otherwise try a newer version of BTD

How do you get rid of them?

**Comment by BaronBeefStick** [comment]
Belt method. https://youtu.be/QjCwT9hHOOk
