### ISSUE TITLE
Ability to edit (or overwrite) "loot filter"

### ISSUE THREAD

**Issue by oliver-phet** [BTNeandertha1/BTDiablo#95]
Is it possible to edit the loot filter applied in the mod? (I have experience with this in PD2) If so, can you point me to the source file(s)?

If not, can another loot filter be applied while using the mod?

**Comment by BaronBeefStick** [comment]
It's pretty time consuming but \Diablo II Resurrected\mods\btdiablo\BTDiablo.mpq\data\local\lng\strings in there youll see item-names.json and more.
