### ISSUE TITLE
Shared Stash extra tabs unaccessible 

### ISSUE THREAD

**Issue by RedVideo** [BTNeandertha1/BTDiablo#97]
![17173551316132257361454661254700](https://github.com/BTNeandertha1/BTDiablo/assets/171511460/8ca26ef6-9818-4360-90b8-4fd1e7e723a2)

**Comment by BaronBeefStick** [comment]
you need to paste the SharedStashSoftCoreV2.d2i and SharedStashHardCoreV2.d2i into your character save file.
